# Default values for tars-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

tars:
  namespace: tars
  data: /data/tars-data
  image: harbor.test.101nd.cn/ai-teacher/tars-framework:v2.5.1
  replicas: 2
  host: test.101nd.cn
  port: 80
  strict: "false"
  mysqlHost: 172.24.140.217
  mysqlUser: tarsAdmin
  mysqlRootPassword : "Tars@2019"
  pullPolicy: IfNotPresent
  pullPolicy: IfNotPresent
  resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
tarsnode:
  image: harbor.test.101nd.cn/ai-teacher/tars-node:v2.0
  replicas: 3
  pullPolicy: IfNotPresent
  resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

mysql:
  enabled: false

  image: mysql:5.6
  rebuild: "false"
  password: "Tars@2019"
  data: /data/mysql-data
  resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
