image: "mysql"
imageTag: "5.6"
rebuild: "false"
imagePullPolicy: IfNotPresent
password: ""
data: /data/mysql-data
resources: {}
nodeSelector: {}
affinity: {}
resources:
  requests:
    memory: 256Mi
    cpu: 100m
