apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
data:
  my.cnf: |
    # Apply this config only on the master.
    [mysqld]
    server-id=1
    log-bin
    expire_logs_days = 30