apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "emqx.name" . }}
    chart: {{ template "emqx.chart" . }}
  name: {{ template "emqx.fullname" . }}
data:
  emqx_dashboard.conf: |-

  acl.conf: |-

  emqx_auth_username.conf: |-
