apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: emqx_dashboard
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: {{ .Release.Namespace }}.{{.Values.emqx.host}}
    http:
      paths:
      - backend:
          serviceName: {{ template "emqx.name" . }}
          servicePort: 18083
        pathType: ImplementationSpecific