apiVersion: v1
kind: Service
metadata:
  name: {{ template "emqx.name" . }}
  namespace: "{{ .Release.Namespace }}"
spec:
  selector:
    app: emqx-3dcp
  ports:
  - name: mqtt
    protocol: TCP
    port: 1883
    targetPort: 1883
  - name: mqttssl
    protocol: TCP
    port: 8883
    targetPort: 8883
  - name: mgmt
    protocol: TCP
    port: 8081
    targetPort: 8081
  - name: ws
    protocol: TCP
    port: 8083
    targetPort: 8083
  - name: wss
    protocol: TCP
    port: 8084
    targetPort: 8084
  - name: dashboard
    protocol: TCP
    port: 18083
    targetPort: 18083
  selector:
    app: {{ template "emqx.name" . }}
